def template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: docker
  name: docker
spec:
  containers:
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
    securityContext:
      privileged: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket
'''


properties([
    parameters([
        string(
            name: 'AWS_REGION',
            defaultValue: 'us-east-1',
            description: 'AWS region for ECR'
        ),
        string(
            name: 'ECR_REPO',
            defaultValue: 'nodejs-nyan-app-jenkins',
            description: 'ECR repository base name'
        ),
        string(
            name: 'IMAGE_NAME',
            defaultValue: 'web',
            description: 'Image name'
        )
    ])
])


podTemplate(cloud: 'kubernetes', label: 'docker', yaml: template) {
    node("docker") {
        container("docker"){
            
            stage("Checkout SCM") {
                git branch: 'main', url: 'https://github.com/K8-Team/web.git'
            }
  
            withCredentials([
                string(credentialsId: 'ecr-creds', variable: 'AWS_ACCOUNT_ID'),
                usernamePassword(credentialsId: 'aws-credentials', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')
            ]) {
                
                stage("Install AWS CLI") {
                    sh """
                    apk add --no-cache python3 py3-pip
                    pip3 install awscli --break-system-packages
                    """
                }

                stage("ECR Login") {
                    sh """
                    export AWS_DEFAULT_REGION=${params.AWS_REGION}
                    aws ecr get-login-password --region ${params.AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com
                    """
                }

                stage("Build Image") {
                    sh """
                    export ECR_REPO_FULL=${params.ECR_REPO}/${params.IMAGE_NAME}
                    docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/\${ECR_REPO_FULL}:${BUILD_NUMBER} .
                    docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/\${ECR_REPO_FULL}:${BUILD_NUMBER} ${AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/\${ECR_REPO_FULL}:latest
                    """
                }

                stage("Push to ECR") {
                    sh """
                    export ECR_REPO_FULL=${params.ECR_REPO}/${params.IMAGE_NAME}
                    docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/\${ECR_REPO_FULL}:${BUILD_NUMBER}
                    docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/\${ECR_REPO_FULL}:latest
                    """
                }
            }
        }
    }
}
